version: '3'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile

    command: bash -c "
      export PYTHONPATH="/home/code";
      uvicorn main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors 
      --reload
      "
    ports:
      - "8000:8000"